# Generated by Django 3.1.7 on 2022-03-21 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_homework'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='is_finisted',
            new_name='is_finished',
        ),
    ]
